name: crowddet
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - ultralytics>=8.3.0
      - opencv-python>=4.8.0
      - numpy>=1.23.0
      - tqdm>=4.66.0

